import { Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import Modal from '../components/Modal'
import StatusBadge from '../components/StatusBadge'
import { formatCurrency } from '../data/mockData'

const blank = { name: '', phone: '', email: '', address: '', orders: 0, purchase: 0, status: 'Active' }
function CustomerForm({ customer, onClose, onSave }) { const [form, setForm] = useState(customer || blank); const [error, setError] = useState(''); const update = (key, value) => setForm({ ...form, [key]: value }); const submit = e => { e.preventDefault(); if (!form.name || !form.phone || !form.email) return setError('Please complete all required fields.'); onSave({ ...form, orders: Number(form.orders || 0), purchase: Number(form.purchase || 0) }) }; return <form className="form-grid" onSubmit={submit}><label>Customer Name *<input value={form.name} onChange={e => update('name', e.target.value)} /></label><label>Phone *<input value={form.phone} onChange={e => update('phone', e.target.value)} /></label><label>Email *<input type="email" value={form.email} onChange={e => update('email', e.target.value)} /></label><label>Status<select value={form.status} onChange={e => update('status', e.target.value)}><option>Active</option><option>Inactive</option></select></label><label>Initial Total Orders<input type="number" min="0" value={form.orders} onChange={e => update('orders', e.target.value)} /></label><label>Initial Total Purchase (₹)<input type="number" min="0" value={form.purchase} onChange={e => update('purchase', e.target.value)} /></label><label className="form-span-2">Address<textarea rows="3" value={form.address} onChange={e => update('address', e.target.value)} /></label>{error && <p className="form-error form-span-2">{error}</p>}<div className="modal-actions form-span-2"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button">{customer ? 'Save Changes' : 'Add Customer'}</button></div></form> }
export default function CustomersPage({ customers, onSaveCustomer, onDeleteCustomer }) { const [query, setQuery] = useState(''); const [modal, setModal] = useState(null); const rows = useMemo(() => customers.filter(item => (item.name + item.email + item.phone).toLowerCase().includes(query.toLowerCase())), [customers, query]); const save = item => { onSaveCustomer(item); setModal(null) }; return <div className="page"><div className="page-intro"><div><h2>Customers</h2><p>Maintain customer contacts and order history.</p></div><button className="primary-button" onClick={() => setModal({ type: 'add' })}><Plus size={17} />Add Customer</button></div><section className="content-card"><div className="table-controls"><label className="table-search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search customers..." /></label></div><div className="table-wrap"><table><thead><tr><th>Customer ID</th><th>Customer Name</th><th>Phone</th><th>Email</th><th>Address</th><th>Total Orders</th><th>Total Purchase</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td>{item.id}</td><td className="strong-cell">{item.name}</td><td>{item.phone}</td><td>{item.email}</td><td>{item.address}</td><td>{item.orders}</td><td>{formatCurrency(item.purchase)}</td><td><StatusBadge status={item.status} /></td><td><div className="row-actions"><button title="View" onClick={() => setModal({ type: 'view', item })}><Eye size={16} /></button><button title="Edit" onClick={() => setModal({ type: 'edit', item })}><Pencil size={16} /></button><button className="delete-action" title="Delete" onClick={() => { if (window.confirm(`Delete ${item.name}?`)) onDeleteCustomer(item.id) }}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div></section>{modal?.type === 'view' && <Modal title="Customer Details" onClose={() => setModal(null)}><div className="detail-list">{[['Customer Name', modal.item.name], ['Customer ID', modal.item.id], ['Phone', modal.item.phone], ['Email', modal.item.email], ['Address', modal.item.address], ['Total Orders', modal.item.orders], ['Total Purchase', formatCurrency(modal.item.purchase)], ['Status', modal.item.status]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="modal-actions"><button className="secondary-button" onClick={() => setModal(null)}>Close</button><button className="primary-button" onClick={() => setModal({ type: 'edit', item: modal.item })}>Edit Customer</button></div></Modal>}{modal?.type === 'add' && <Modal title="Add Customer" onClose={() => setModal(null)}><CustomerForm onClose={() => setModal(null)} onSave={save} /></Modal>}{modal?.type === 'edit' && <Modal title="Edit Customer" onClose={() => setModal(null)}><CustomerForm customer={modal.item} onClose={() => setModal(null)} onSave={save} /></Modal>}</div> }
